### ISSUE TITLE
Questions and Thanks!

### ISSUE THREAD

**Issue by asilverstein** [macedd/wp-laravel#1]
Greetings Thiago,

I've just convinced a customer that using WP as a front end for a Laravel app is the best architecture for a new project. Your code looks like a great way to make this happen. Thank you for sharing it. I have a couple of questions:

1) Does this support blade templating?
2) What do you think about the Corcel project? https://github.com/corcel/corcel

Thanks again,
Alex

**Comment by masterseoonline** [comment]
its very very simple plain code,
https://github.com/thiagof/wp-laravel/blob/master/wp-laravel/includes/actions.php#L16
may can break your site, if you using deep class like routin
there is more cleaver code can do it neatly without crash

**Comment by macedd** [comment]
Hello Alex, sorry for the delay in responding.

I think Corcel project is great and I recommend it as the best way to fetch data from WordPress. Also if you are creating multiple post types it will be much cleaner to model each one of them with Corcel.

In relation to `blade` templates, I understand it's fully supported.

```php
$view = view('example');
echo $view->render(); // Hello, World!
echo $view;  // Hello, World!
```

**Comment by asilverstein** [comment]
Thanks Thiago, I'll give it a try.
